[tool.poetry]
name = "mlproject-exercise"
version = "0.1.0"
description = ""
authors = ["sdudiak <sdudiak@student.agh.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
